---
name: gdsfactory
channels:
    - conda-forge
dependencies:
    - python
    - gdspy
    - triangle
    - nbgitpuller
    - ffmpeg
    - numpy
    - scipy
    - pymeep
    - pip
    - pip:
          - -r requirements.txt
          - -r requirements_dev.txt
          - nlopt
          - matplotlib
          - autograd
          - jax
