[tool.poetry]
name = "gdsfactory"
version = "3.8.14"
description = "library for GDS layouts"
authors = ["gdsfactory community"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7"
click = "^8.0.3"
gdspy = "^1.6.10"
ipympl = "^0.8.4"
jsondiff = "^1.3.0"
loguru = "^0.5.3"
lytest = "^0.0.20"
matplotlib = "^3.5.1"
networkx = "^2.6.3"
omegaconf = "^2.1.1"
phidl = "^1.6.0"
picwriter = "^0.5"
pydantic = "^1.8.2"
Pyqtree = "^1.0.0"
pytest = "^6.2.5"
pytest-regressions = "^2.2.0"
qrcode = "^7.3.1"
rectpack = "^0.2.2"
scikit-image = "^0.19.1"
semantic-version = "^2.8.5"
Shapely = "^1.8.0"
toolz = "^0.11.2"
trimesh = "^3.9.36"
typing-extensions = "^4.0.1"
xmltodict = "^0.12.0"

[tool.poetry.dev-dependencies]
doc8 = {version = "^0.10.1", optional = true}
docutils = {version = "^0.18.1", optional = true}
flake8 = {version = "^4.0.1", optional = true}
flake8-rst-docstrings = {version = "^0.2.5", optional = true}
ipykernel = {version = "^6.6.0", optional = true}
mypy = {version = "^0.920", optional = true}
nbsphinx = {version = "^0.8.7", optional = true}
nbval = {version = "^0.9.6", optional = true}
pre-commit = {version = "^2.16.0", optional = true}
pydocstyle = {version = "^6.1.1", optional = true}
pyglet = {version = "^1.5.21", optional = true}
pytest-cov = {version = "^3.0.0", optional = true}
recommonmark = {version = "^0.7.1", optional = true}
sphinx-autodoc-typehints = {version = "^1.12.0", optional = true}
sphinx-click = {version = "^3.0.2", optional = true}
sphinx-markdown-tables = {version = "^0.0.15", optional = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
xdoctest = {version = "^0.15.10", optional = true}
tox = {version = "^3.24.4", optional = true}

[tool.poetry.extras]
full = ['klayout', 'tidy3d', 'triangle']


[tool.poetry.scripts]
gf = "gdsfactory.gf:gf"
