cells:
  bend_euler_40e83c11:
    changed:
      cross_section:
        function: cross_section
        layer:
        - 34
        - 0
        layers_cladding:
        - - 36
          - 0
        width: 1
      decorator:
        function: add_pins
    default:
      angle: 90
      cross_section:
        function: cross_section
      direction: ccw
      npoints: 720
      p: 0.5
      with_arc_floorplan: true
      with_cladding_box: true
    dy: 10
    full:
      angle: 90
      cross_section:
        function: cross_section
        layer:
        - 34
        - 0
        layers_cladding:
        - - 36
          - 0
        width: 1
      decorator:
        function: add_pins
      direction: ccw
      npoints: 720
      p: 0.5
      with_arc_floorplan: true
      with_cladding_box: true
    function_name: bend_euler
    info_version: 1
    length: 16.637
    module: gdsfactory.components.bend_euler
    name: bend_euler_40e83c11
    radius: 10
    radius_min: 7.061
info:
  changed:
    cross_section:
      function: cross_section
      layer:
      - 34
      - 0
      layers_cladding:
      - - 36
        - 0
      width: 1
    decorator:
      function: add_pins
  default:
    angle: 90
    cross_section:
      function: cross_section
    direction: ccw
    npoints: 720
    p: 0.5
    with_arc_floorplan: true
    with_cladding_box: true
  dy: 10
  full:
    angle: 90
    cross_section:
      function: cross_section
      layer:
      - 34
      - 0
      layers_cladding:
      - - 36
        - 0
      width: 1
    decorator:
      function: add_pins
    direction: ccw
    npoints: 720
    p: 0.5
    with_arc_floorplan: true
    with_cladding_box: true
  function_name: bend_euler
  info_version: 1
  length: 16.637
  module: gdsfactory.components.bend_euler
  name: bend_euler_40e83c11
  radius: 10
  radius_min: 7.061
ports:
  o1:
    layer:
    - 34
    - 0
    midpoint:
    - 0
    - 0
    name: o1
    orientation: 180
    port_type: optical
    width: 1
  o2:
    layer:
    - 34
    - 0
    midpoint:
    - 10
    - 10
    name: o2
    orientation: 90
    port_type: optical
    width: 1
version: 0.0.1
