cells:
  bend_euler_0c3469c8:
    changed:
      auto_widen: true
      cross_section:
        function: cross_section
    default:
      angle: 90
      cross_section:
        function: cross_section
      direction: ccw
      npoints: 720
      p: 0.5
      with_arc_floorplan: true
      with_cladding_box: true
    dy: 10
    full:
      angle: 90
      auto_widen: true
      cross_section:
        function: cross_section
      direction: ccw
      npoints: 720
      p: 0.5
      with_arc_floorplan: true
      with_cladding_box: true
    function_name: bend_euler
    info_version: 1
    length: 16.637
    module: gdsfactory.components.bend_euler
    name: bend_euler_0c3469c8
    radius: 10
    radius_min: 7.061
  bend_euler_1da190e0:
    changed:
      cross_section:
        function: cross_section
    default:
      angle: 90
      cross_section:
        function: cross_section
      direction: ccw
      npoints: 720
      p: 0.5
      with_arc_floorplan: true
      with_cladding_box: true
    dy: 10
    full:
      angle: 90
      cross_section:
        function: cross_section
      direction: ccw
      npoints: 720
      p: 0.5
      with_arc_floorplan: true
      with_cladding_box: true
    function_name: bend_euler
    info_version: 1
    length: 16.637
    module: gdsfactory.components.bend_euler
    name: bend_euler_1da190e0
    radius: 10
    radius_min: 7.061
  circle_602e85fd:
    changed:
      layer:
      - 203
      - 0
      radius: 5.5
    default:
      angle_resolution: 2.5
      layer:
      - 1
      - 0
      radius: 10
    full:
      angle_resolution: 2.5
      layer:
      - 203
      - 0
      radius: 5.5
    function_name: circle
    info_version: 1
    module: gdsfactory.components.circle
    name: circle_602e85fd
  coupler_70441075:
    changed:
      gap: 0.2
      length: 5
    default:
      coupler_straight:
        function: coupler_straight
      coupler_symmetric:
        function: coupler_symmetric
      cross_section:
        function: cross_section
      dx: 10
      dy: 5
      gap: 0.236
      length: 20
    full:
      coupler_straight:
        function: coupler_straight
      coupler_symmetric:
        function: coupler_symmetric
      cross_section:
        function: cross_section
      dx: 10
      dy: 5
      gap: 0.2
      length: 5
    function_name: coupler
    info_version: 1
    length: 10.319
    min_bend_radius: 9.387
    module: gdsfactory.components.coupler
    name: coupler_70441075
  coupler_70441075_add_fi_49620dbe:
    changed:
      component: coupler_70441075
      optical_routing_type: 1
    child:
      changed:
        gap: 0.2
        length: 5
      default:
        coupler_straight:
          function: coupler_straight
        coupler_symmetric:
          function: coupler_symmetric
        cross_section:
          function: cross_section
        dx: 10
        dy: 5
        gap: 0.236
        length: 20
      full:
        coupler_straight:
          function: coupler_straight
        coupler_symmetric:
          function: coupler_symmetric
        cross_section:
          function: cross_section
        dx: 10
        dy: 5
        gap: 0.2
        length: 5
      function_name: coupler
      info_version: 1
      length: 10.319
      min_bend_radius: 9.387
      module: gdsfactory.components.coupler
      name: coupler_70441075
    default:
      bend:
        function: bend_euler
      component_name: null
      cross_section:
        function: cross_section
      gc_port_labels: null
      gc_port_name: o1
      get_input_labels_function:
        function: get_input_labels
      grating_coupler:
        function: grating_coupler_elliptical_trenches
        polarization: te
        taper_angle: 35
      layer_label:
      - 66
      - 0
      select_ports:
        function: select_ports
        port_type: optical
      straight:
        function: straight
    full:
      bend:
        function: bend_euler
      component: coupler_70441075
      component_name: null
      cross_section:
        function: cross_section
      gc_port_labels: null
      gc_port_name: o1
      get_input_labels_function:
        function: get_input_labels
      grating_coupler:
        function: grating_coupler_elliptical_trenches
        polarization: te
        taper_angle: 35
      layer_label:
      - 66
      - 0
      optical_routing_type: 1
      select_ports:
        function: select_ports
        port_type: optical
      straight:
        function: straight
    function_name: add_fiber_array
    info_version: 1
    module: gdsfactory.routing.add_fiber_array
    name: coupler_70441075_add_fi_49620dbe
  grating_coupler_ellipti_b632d295:
    changed:
      polarization: te
      taper_angle: 35
    default:
      end_straight_length: 0.2
      fiber_angle: 15
      fiber_marker_layer:
      - 203
      - 0
      fiber_marker_width: 11
      grating_line_width: 0.343
      layer:
      - 1
      - 0
      layer_trench:
      - 2
      - 0
      n_periods: 30
      ncladding: 1.443
      neff: 2.638
      p_start: 26
      polarization: te
      taper_angle: 30
      taper_length: 16.6
      trenches_extra_angle: 9
      wavelength: 1.53
      wg_width: 0.5
    full:
      end_straight_length: 0.2
      fiber_angle: 15
      fiber_marker_layer:
      - 203
      - 0
      fiber_marker_width: 11
      grating_line_width: 0.343
      layer:
      - 1
      - 0
      layer_trench:
      - 2
      - 0
      n_periods: 30
      ncladding: 1.443
      neff: 2.638
      p_start: 26
      polarization: te
      taper_angle: 35
      taper_length: 16.6
      trenches_extra_angle: 9
      wavelength: 1.53
      wg_width: 0.5
    function_name: grating_coupler_elliptical_trenches
    info_version: 1
    module: gdsfactory.components.grating_coupler_elliptical_trenches
    name: grating_coupler_ellipti_b632d295
    period: 0.6759999999999999
    polarization: te
    wavelength: 1.53
  straight_02352a98:
    changed:
      auto_widen: true
      cross_section:
        function: cross_section
      length: 1
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      auto_widen: true
      cross_section:
        function: cross_section
      length: 1
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 1
    module: gdsfactory.components.straight
    name: straight_02352a98
    width: 0.5
  straight_06b7497a:
    changed:
      cross_section:
        function: cross_section
      length: 43.5
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 43.5
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 43.5
    module: gdsfactory.components.straight
    name: straight_06b7497a
    width: 0.5
  straight_1795b20c:
    changed:
      cross_section:
        function: cross_section
      length: 6.25
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 6.25
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 6.25
    module: gdsfactory.components.straight
    name: straight_1795b20c
    width: 0.5
  straight_650b3161:
    changed:
      cross_section:
        function: cross_section
      length: 12.25
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 12.25
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 12.25
    module: gdsfactory.components.straight
    name: straight_650b3161
    width: 0.5
  straight_6c1c731d:
    changed:
      cross_section:
        function: cross_section
      length: 20
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 20
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 20
    module: gdsfactory.components.straight
    name: straight_6c1c731d
    width: 0.5
  straight_763e1ea3:
    changed:
      cross_section:
        function: cross_section
      length: 35.552
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 35.552
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 35.552
    module: gdsfactory.components.straight
    name: straight_763e1ea3
    width: 0.5
  straight_7a1490a4:
    changed:
      auto_widen: true
      cross_section:
        function: cross_section
      length: 0.5
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      auto_widen: true
      cross_section:
        function: cross_section
      length: 0.5
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 0.5
    module: gdsfactory.components.straight
    name: straight_7a1490a4
    width: 0.5
  straight_7e6a8575:
    changed:
      auto_widen: true
      cross_section:
        function: cross_section
      length: 5.5
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      auto_widen: true
      cross_section:
        function: cross_section
      length: 5.5
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 5.5
    module: gdsfactory.components.straight
    name: straight_7e6a8575
    width: 0.5
  straight_b3ed30dd:
    changed:
      auto_widen: true
      cross_section:
        function: cross_section
      length: 7
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      auto_widen: true
      cross_section:
        function: cross_section
      length: 7
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 7
    module: gdsfactory.components.straight
    name: straight_b3ed30dd
    width: 0.5
  straight_bc29f1fe:
    changed:
      cross_section:
        function: cross_section
      length: 17
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 17
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 17
    module: gdsfactory.components.straight
    name: straight_bc29f1fe
    width: 0.5
  straight_c7b35a9f:
    changed:
      cross_section:
        function: cross_section
      length: 11
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 11
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 11
    module: gdsfactory.components.straight
    name: straight_c7b35a9f
    width: 0.5
  straight_ca7e7c8f:
    changed:
      cross_section:
        function: cross_section
      length: 488
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 488
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 488
    module: gdsfactory.components.straight
    name: straight_ca7e7c8f
    width: 0.5
  straight_ef8909f9:
    changed:
      cross_section:
        function: cross_section
      length: 141
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 141
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 141
    module: gdsfactory.components.straight
    name: straight_ef8909f9
    width: 0.5
info:
  changed:
    component: coupler_70441075
    optical_routing_type: 1
  child:
    changed:
      gap: 0.2
      length: 5
    default:
      coupler_straight:
        function: coupler_straight
      coupler_symmetric:
        function: coupler_symmetric
      cross_section:
        function: cross_section
      dx: 10
      dy: 5
      gap: 0.236
      length: 20
    full:
      coupler_straight:
        function: coupler_straight
      coupler_symmetric:
        function: coupler_symmetric
      cross_section:
        function: cross_section
      dx: 10
      dy: 5
      gap: 0.2
      length: 5
    function_name: coupler
    info_version: 1
    length: 10.319
    min_bend_radius: 9.387
    module: gdsfactory.components.coupler
    name: coupler_70441075
  default:
    bend:
      function: bend_euler
    component_name: null
    cross_section:
      function: cross_section
    gc_port_labels: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      polarization: te
      taper_angle: 35
    layer_label:
    - 66
    - 0
    select_ports:
      function: select_ports
      port_type: optical
    straight:
      function: straight
  full:
    bend:
      function: bend_euler
    component: coupler_70441075
    component_name: null
    cross_section:
      function: cross_section
    gc_port_labels: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      polarization: te
      taper_angle: 35
    layer_label:
    - 66
    - 0
    optical_routing_type: 1
    select_ports:
      function: select_ports
      port_type: optical
    straight:
      function: straight
  function_name: add_fiber_array
  info_version: 1
  module: gdsfactory.routing.add_fiber_array
  name: coupler_70441075_add_fi_49620dbe
ports:
  vertical_te_00:
    layer:
    - 203
    - 0
    midpoint:
    - -188
    - -82.169
    name: vertical_te_00
    orientation: 270
    port_type: vertical_te
    width: 11
  vertical_te_01:
    layer:
    - 203
    - 0
    midpoint:
    - -61.00000000000001
    - -82.169
    name: vertical_te_01
    orientation: 270
    port_type: vertical_te
    width: 11
  vertical_te_02:
    layer:
    - 203
    - 0
    midpoint:
    - 66
    - -82.169
    name: vertical_te_02
    orientation: 270
    port_type: vertical_te
    width: 11
  vertical_te_03:
    layer:
    - 203
    - 0
    midpoint:
    - 193
    - -82.169
    name: vertical_te_03
    orientation: 270
    port_type: vertical_te
    width: 11
version: 0.0.1
