cells:
  bend_euler_1da190e0:
    changed:
      cross_section:
        function: cross_section
    default:
      angle: 90
      cross_section:
        function: cross_section
      direction: ccw
      npoints: 720
      p: 0.5
      with_arc_floorplan: true
      with_cladding_box: true
    dy: 10
    full:
      angle: 90
      cross_section:
        function: cross_section
      direction: ccw
      npoints: 720
      p: 0.5
      with_arc_floorplan: true
      with_cladding_box: true
    function_name: bend_euler
    info_version: 1
    length: 16.637
    module: gdsfactory.components.bend_euler
    name: bend_euler_1da190e0
    radius: 10
    radius_min: 7.061
  circle_602e85fd:
    changed:
      layer:
      - 203
      - 0
      radius: 5.5
    default:
      angle_resolution: 2.5
      layer:
      - 1
      - 0
      radius: 10
    full:
      angle_resolution: 2.5
      layer:
      - 203
      - 0
      radius: 5.5
    function_name: circle
    info_version: 1
    module: gdsfactory.components.circle
    name: circle_602e85fd
  grating_coupler_ellipti_b632d295:
    changed:
      polarization: te
      taper_angle: 35
    default:
      end_straight_length: 0.2
      fiber_angle: 15
      fiber_marker_layer:
      - 203
      - 0
      fiber_marker_width: 11
      grating_line_width: 0.343
      layer:
      - 1
      - 0
      layer_trench:
      - 2
      - 0
      n_periods: 30
      ncladding: 1.443
      neff: 2.638
      p_start: 26
      polarization: te
      taper_angle: 30
      taper_length: 16.6
      trenches_extra_angle: 9
      wavelength: 1.53
      wg_width: 0.5
    full:
      end_straight_length: 0.2
      fiber_angle: 15
      fiber_marker_layer:
      - 203
      - 0
      fiber_marker_width: 11
      grating_line_width: 0.343
      layer:
      - 1
      - 0
      layer_trench:
      - 2
      - 0
      n_periods: 30
      ncladding: 1.443
      neff: 2.638
      p_start: 26
      polarization: te
      taper_angle: 35
      taper_length: 16.6
      trenches_extra_angle: 9
      wavelength: 1.53
      wg_width: 0.5
    function_name: grating_coupler_elliptical_trenches
    info_version: 1
    module: gdsfactory.components.grating_coupler_elliptical_trenches
    name: grating_coupler_ellipti_b632d295
    period: 0.6759999999999999
    polarization: te
    wavelength: 1.53
  straight_06b7497a:
    changed:
      cross_section:
        function: cross_section
      length: 43.5
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 43.5
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 43.5
    module: gdsfactory.components.straight
    name: straight_06b7497a
    width: 0.5
  straight_35a9b97f:
    changed:
      cross_section:
        function: cross_section
      length: 33.5
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 33.5
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 33.5
    module: gdsfactory.components.straight
    name: straight_35a9b97f
    width: 0.5
  straight_373b1ebb:
    changed:
      length: 20
      width: 2
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 20
      npoints: 2
      width: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 20
    module: gdsfactory.components.straight
    name: straight_373b1ebb
    width: 2
  straight_373b1ebb_add_f_0217bd04:
    changed:
      component: straight_373b1ebb_add_t_9b5da3e4
      optical_routing_type: 0
    child:
      changed:
        component: straight_373b1ebb
      child:
        changed:
          length: 20
          width: 2
        default:
          cross_section:
            function: cross_section
          length: 10
          npoints: 2
          with_cladding_box: true
        full:
          cross_section:
            function: cross_section
          length: 20
          npoints: 2
          width: 2
          with_cladding_box: true
        function_name: straight
        info_version: 1
        length: 20
        module: gdsfactory.components.straight
        name: straight_373b1ebb
        width: 2
      default:
        select_ports:
          function: select_ports
          port_type: optical
        taper:
          function: taper
        taper_port_name1: o1
        taper_port_name2: o2
      full:
        component: straight_373b1ebb
        select_ports:
          function: select_ports
          port_type: optical
        taper:
          function: taper
        taper_port_name1: o1
        taper_port_name2: o2
      function_name: add_tapers
      info_version: 1
      module: gdsfactory.add_tapers
      name: straight_373b1ebb_add_t_9b5da3e4
    default:
      bend:
        function: bend_euler
      component_name: null
      cross_section:
        function: cross_section
      gc_port_labels: null
      gc_port_name: o1
      get_input_labels_function:
        function: get_input_labels
      grating_coupler:
        function: grating_coupler_elliptical_trenches
        polarization: te
        taper_angle: 35
      layer_label:
      - 66
      - 0
      select_ports:
        function: select_ports
        port_type: optical
      straight:
        function: straight
    full:
      bend:
        function: bend_euler
      component: straight_373b1ebb_add_t_9b5da3e4
      component_name: null
      cross_section:
        function: cross_section
      gc_port_labels: null
      gc_port_name: o1
      get_input_labels_function:
        function: get_input_labels
      grating_coupler:
        function: grating_coupler_elliptical_trenches
        polarization: te
        taper_angle: 35
      layer_label:
      - 66
      - 0
      optical_routing_type: 0
      select_ports:
        function: select_ports
        port_type: optical
      straight:
        function: straight
    function_name: add_fiber_array
    info_version: 1
    module: gdsfactory.routing.add_fiber_array
    name: straight_373b1ebb_add_f_0217bd04
  straight_373b1ebb_add_t_9b5da3e4:
    changed:
      component: straight_373b1ebb
    child:
      changed:
        length: 20
        width: 2
      default:
        cross_section:
          function: cross_section
        length: 10
        npoints: 2
        with_cladding_box: true
      full:
        cross_section:
          function: cross_section
        length: 20
        npoints: 2
        width: 2
        with_cladding_box: true
      function_name: straight
      info_version: 1
      length: 20
      module: gdsfactory.components.straight
      name: straight_373b1ebb
      width: 2
    default:
      select_ports:
        function: select_ports
        port_type: optical
      taper:
        function: taper
      taper_port_name1: o1
      taper_port_name2: o2
    full:
      component: straight_373b1ebb
      select_ports:
        function: select_ports
        port_type: optical
      taper:
        function: taper
      taper_port_name1: o1
      taper_port_name2: o2
    function_name: add_tapers
    info_version: 1
    module: gdsfactory.add_tapers
    name: straight_373b1ebb_add_t_9b5da3e4
  straight_763e1ea3:
    changed:
      cross_section:
        function: cross_section
      length: 35.552
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 35.552
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 35.552
    module: gdsfactory.components.straight
    name: straight_763e1ea3
    width: 0.5
  straight_7e153a04:
    changed:
      cross_section:
        function: cross_section
      length: 18.5
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 18.5
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 18.5
    module: gdsfactory.components.straight
    name: straight_7e153a04
    width: 0.5
  straight_c4828fc0:
    changed:
      cross_section:
        function: cross_section
      length: 234
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 234
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 234
    module: gdsfactory.components.straight
    name: straight_c4828fc0
    width: 0.5
  taper_bea08b71:
    changed:
      width2: 2
    default:
      cross_section:
        function: cross_section
      length: 10
      port: null
      width1: 0.5
      width2: null
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 10
      port: null
      width1: 0.5
      width2: 2
      with_cladding_box: true
    function_name: taper
    info_version: 1
    length: 10
    module: gdsfactory.components.taper
    name: taper_bea08b71
    width1: 0.5
    width2: 2
info:
  changed:
    component: straight_373b1ebb_add_t_9b5da3e4
    optical_routing_type: 0
  child:
    changed:
      component: straight_373b1ebb
    child:
      changed:
        length: 20
        width: 2
      default:
        cross_section:
          function: cross_section
        length: 10
        npoints: 2
        with_cladding_box: true
      full:
        cross_section:
          function: cross_section
        length: 20
        npoints: 2
        width: 2
        with_cladding_box: true
      function_name: straight
      info_version: 1
      length: 20
      module: gdsfactory.components.straight
      name: straight_373b1ebb
      width: 2
    default:
      select_ports:
        function: select_ports
        port_type: optical
      taper:
        function: taper
      taper_port_name1: o1
      taper_port_name2: o2
    full:
      component: straight_373b1ebb
      select_ports:
        function: select_ports
        port_type: optical
      taper:
        function: taper
      taper_port_name1: o1
      taper_port_name2: o2
    function_name: add_tapers
    info_version: 1
    module: gdsfactory.add_tapers
    name: straight_373b1ebb_add_t_9b5da3e4
  default:
    bend:
      function: bend_euler
    component_name: null
    cross_section:
      function: cross_section
    gc_port_labels: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      polarization: te
      taper_angle: 35
    layer_label:
    - 66
    - 0
    select_ports:
      function: select_ports
      port_type: optical
    straight:
      function: straight
  full:
    bend:
      function: bend_euler
    component: straight_373b1ebb_add_t_9b5da3e4
    component_name: null
    cross_section:
      function: cross_section
    gc_port_labels: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      polarization: te
      taper_angle: 35
    layer_label:
    - 66
    - 0
    optical_routing_type: 0
    select_ports:
      function: select_ports
      port_type: optical
    straight:
      function: straight
  function_name: add_fiber_array
  info_version: 1
  module: gdsfactory.routing.add_fiber_array
  name: straight_373b1ebb_add_f_0217bd04
ports:
  vertical_te_00:
    layer:
    - 203
    - 0
    midpoint:
    - -53.50000000000001
    - -54.769
    name: vertical_te_00
    orientation: 270
    port_type: vertical_te
    width: 11
  vertical_te_01:
    layer:
    - 203
    - 0
    midpoint:
    - 73.5
    - -54.769
    name: vertical_te_01
    orientation: 270
    port_type: vertical_te
    width: 11
version: 0.0.1
