cells:
  bend_euler_1da190e0:
    changed:
      cross_section:
        function: cross_section
    default:
      angle: 90
      cross_section:
        function: cross_section
      direction: ccw
      npoints: 720
      p: 0.5
      with_arc_floorplan: true
      with_cladding_box: true
    dy: 10
    full:
      angle: 90
      cross_section:
        function: cross_section
      direction: ccw
      npoints: 720
      p: 0.5
      with_arc_floorplan: true
      with_cladding_box: true
    function_name: bend_euler
    info_version: 1
    length: 16.637
    module: gdsfactory.components.bend_euler
    name: bend_euler_1da190e0
    radius: 10
    radius_min: 7.061
  circle_602e85fd:
    changed:
      layer:
      - 203
      - 0
      radius: 5.5
    default:
      angle_resolution: 2.5
      layer:
      - 1
      - 0
      radius: 10
    full:
      angle_resolution: 2.5
      layer:
      - 203
      - 0
      radius: 5.5
    function_name: circle
    info_version: 1
    module: gdsfactory.components.circle
    name: circle_602e85fd
  coupler_12df0178:
    changed:
      gap: 0.244
      length: 5.67
    default:
      coupler_straight:
        function: coupler_straight
      coupler_symmetric:
        function: coupler_symmetric
      cross_section:
        function: cross_section
      dx: 10
      dy: 5
      gap: 0.236
      length: 20
    full:
      coupler_straight:
        function: coupler_straight
      coupler_symmetric:
        function: coupler_symmetric
      cross_section:
        function: cross_section
      dx: 10
      dy: 5
      gap: 0.244
      length: 5.67
    function_name: coupler
    info_version: 1
    length: 10.313
    min_bend_radius: 9.465
    module: gdsfactory.components.coupler
    name: coupler_12df0178
  coupler_12df0178_add_fi_b940b28a:
    changed:
      component: coupler_12df0178
      optical_routing_type: 0
    child:
      changed:
        gap: 0.244
        length: 5.67
      default:
        coupler_straight:
          function: coupler_straight
        coupler_symmetric:
          function: coupler_symmetric
        cross_section:
          function: cross_section
        dx: 10
        dy: 5
        gap: 0.236
        length: 20
      full:
        coupler_straight:
          function: coupler_straight
        coupler_symmetric:
          function: coupler_symmetric
        cross_section:
          function: cross_section
        dx: 10
        dy: 5
        gap: 0.244
        length: 5.67
      function_name: coupler
      info_version: 1
      length: 10.313
      min_bend_radius: 9.465
      module: gdsfactory.components.coupler
      name: coupler_12df0178
    default:
      bend:
        function: bend_euler
      component_name: null
      cross_section:
        function: cross_section
      gc_port_labels: null
      gc_port_name: o1
      get_input_labels_function:
        function: get_input_labels
      grating_coupler:
        function: grating_coupler_elliptical_trenches
        polarization: te
        taper_angle: 35
      layer_label:
      - 66
      - 0
      select_ports:
        function: select_ports
        port_type: optical
      straight:
        function: straight
    full:
      bend:
        function: bend_euler
      component: coupler_12df0178
      component_name: null
      cross_section:
        function: cross_section
      gc_port_labels: null
      gc_port_name: o1
      get_input_labels_function:
        function: get_input_labels
      grating_coupler:
        function: grating_coupler_elliptical_trenches
        polarization: te
        taper_angle: 35
      layer_label:
      - 66
      - 0
      optical_routing_type: 0
      select_ports:
        function: select_ports
        port_type: optical
      straight:
        function: straight
    function_name: add_fiber_array
    info_version: 1
    module: gdsfactory.routing.add_fiber_array
    name: coupler_12df0178_add_fi_b940b28a
  grating_coupler_ellipti_b632d295:
    changed:
      polarization: te
      taper_angle: 35
    default:
      end_straight_length: 0.2
      fiber_angle: 15
      fiber_marker_layer:
      - 203
      - 0
      fiber_marker_width: 11
      grating_line_width: 0.343
      layer:
      - 1
      - 0
      layer_trench:
      - 2
      - 0
      n_periods: 30
      ncladding: 1.443
      neff: 2.638
      p_start: 26
      polarization: te
      taper_angle: 30
      taper_length: 16.6
      trenches_extra_angle: 9
      wavelength: 1.53
      wg_width: 0.5
    full:
      end_straight_length: 0.2
      fiber_angle: 15
      fiber_marker_layer:
      - 203
      - 0
      fiber_marker_width: 11
      grating_line_width: 0.343
      layer:
      - 1
      - 0
      layer_trench:
      - 2
      - 0
      n_periods: 30
      ncladding: 1.443
      neff: 2.638
      p_start: 26
      polarization: te
      taper_angle: 35
      taper_length: 16.6
      trenches_extra_angle: 9
      wavelength: 1.53
      wg_width: 0.5
    function_name: grating_coupler_elliptical_trenches
    info_version: 1
    module: gdsfactory.components.grating_coupler_elliptical_trenches
    name: grating_coupler_ellipti_b632d295
    period: 0.6759999999999999
    polarization: te
    wavelength: 1.53
  straight_06b7497a:
    changed:
      cross_section:
        function: cross_section
      length: 43.5
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 43.5
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 43.5
    module: gdsfactory.components.straight
    name: straight_06b7497a
    width: 0.5
  straight_42f2ed13:
    changed:
      cross_section:
        function: cross_section
      length: 43.672
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 43.672
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 43.672
    module: gdsfactory.components.straight
    name: straight_42f2ed13
    width: 0.5
  straight_63b82305:
    changed:
      cross_section:
        function: cross_section
      length: 40.63
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 40.63
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 40.63
    module: gdsfactory.components.straight
    name: straight_63b82305
    width: 0.5
  straight_70301b8e:
    changed:
      cross_section:
        function: cross_section
      length: 48.672
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 48.672
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 48.672
    module: gdsfactory.components.straight
    name: straight_70301b8e
    width: 0.5
  straight_763e1ea3:
    changed:
      cross_section:
        function: cross_section
      length: 35.552
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 35.552
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 35.552
    module: gdsfactory.components.straight
    name: straight_763e1ea3
    width: 0.5
  straight_8d8c66e1:
    changed:
      cross_section:
        function: cross_section
      length: 167.63
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 167.63
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 167.63
    module: gdsfactory.components.straight
    name: straight_8d8c66e1
    width: 0.5
  straight_962f27ff:
    changed:
      cross_section:
        function: cross_section
      length: 167.7
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 167.7
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 167.7
    module: gdsfactory.components.straight
    name: straight_962f27ff
    width: 0.5
  straight_ca7e7c8f:
    changed:
      cross_section:
        function: cross_section
      length: 488
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 488
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 488
    module: gdsfactory.components.straight
    name: straight_ca7e7c8f
    width: 0.5
  straight_f24061d4:
    changed:
      cross_section:
        function: cross_section
      length: 40.7
    default:
      cross_section:
        function: cross_section
      length: 10
      npoints: 2
      with_cladding_box: true
    full:
      cross_section:
        function: cross_section
      length: 40.7
      npoints: 2
      with_cladding_box: true
    function_name: straight
    info_version: 1
    length: 40.7
    module: gdsfactory.components.straight
    name: straight_f24061d4
    width: 0.5
info:
  changed:
    component: coupler_12df0178
    optical_routing_type: 0
  child:
    changed:
      gap: 0.244
      length: 5.67
    default:
      coupler_straight:
        function: coupler_straight
      coupler_symmetric:
        function: coupler_symmetric
      cross_section:
        function: cross_section
      dx: 10
      dy: 5
      gap: 0.236
      length: 20
    full:
      coupler_straight:
        function: coupler_straight
      coupler_symmetric:
        function: coupler_symmetric
      cross_section:
        function: cross_section
      dx: 10
      dy: 5
      gap: 0.244
      length: 5.67
    function_name: coupler
    info_version: 1
    length: 10.313
    min_bend_radius: 9.465
    module: gdsfactory.components.coupler
    name: coupler_12df0178
  default:
    bend:
      function: bend_euler
    component_name: null
    cross_section:
      function: cross_section
    gc_port_labels: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      polarization: te
      taper_angle: 35
    layer_label:
    - 66
    - 0
    select_ports:
      function: select_ports
      port_type: optical
    straight:
      function: straight
  full:
    bend:
      function: bend_euler
    component: coupler_12df0178
    component_name: null
    cross_section:
      function: cross_section
    gc_port_labels: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      polarization: te
      taper_angle: 35
    layer_label:
    - 66
    - 0
    optical_routing_type: 0
    select_ports:
      function: select_ports
      port_type: optical
    straight:
      function: straight
  function_name: add_fiber_array
  info_version: 1
  module: gdsfactory.routing.add_fiber_array
  name: coupler_12df0178_add_fi_b940b28a
ports:
  vertical_te_00:
    layer:
    - 203
    - 0
    midpoint:
    - -187.7
    - -82.069
    name: vertical_te_00
    orientation: 270
    port_type: vertical_te
    width: 11
  vertical_te_01:
    layer:
    - 203
    - 0
    midpoint:
    - -60.699999999999996
    - -82.069
    name: vertical_te_01
    orientation: 270
    port_type: vertical_te
    width: 11
  vertical_te_02:
    layer:
    - 203
    - 0
    midpoint:
    - 66.30000000000001
    - -82.069
    name: vertical_te_02
    orientation: 270
    port_type: vertical_te
    width: 11
  vertical_te_03:
    layer:
    - 203
    - 0
    midpoint:
    - 193.3
    - -82.069
    name: vertical_te_03
    orientation: 270
    port_type: vertical_te
    width: 11
version: 0.0.1
