---
name: Test documentation

on:
  pull_request:
  push:
  schedule:
    - cron: 0 2 * * * # run at 2 AM UTC

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 12
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Make conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9 # Python version to build the html sphinx documentation
          environment-file: environment.yml    # Path to the documentation conda environment
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Install dependencies
        run: |
          mkdir -p $HOME/.tidy3d
          echo ${{ secrets.TIDY3D_EMAIL }}  > $HOME/.tidy3d/email
          echo ${{ secrets.TIDY3D_PASSWORD }} > $HOME/.tidy3d/passwd
          python -m pip install --upgrade pip
          sudo apt install pandoc
          pip install -e .[pip]
      - name: Install dependencies
        run: |
          make install
          # conda env update --file environment.yml --name base
          # conda activate base
      - name: Test documentation
        run: |
          cd docs
          make html
