name: Sphinx docs to gh-pages

on:
  push:
    branches:
      - master

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Make conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9 # Python version to build the html sphinx documentation
          environment-file: environment.yml    # Path to the documentation conda environment
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Installing the library
        shell: bash -l {0}
        run: |
          mkdir -p $HOME/.tidy3d
          echo ${{ secrets.TIDY3D_EMAIL }}  > $HOME/.tidy3d/email
          echo ${{ secrets.TIDY3D_PASSWORD }} > $HOME/.tidy3d/passwd
          pip install -e .[pip]
      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0-beta.2
        with:
          branch: master
          dir_docs: docs
          sphinxopts: ''
