# https://github.com/conda-incubator/setup-miniconda
# https://github.com/actions/starter-workflows/blob/main/ci/python-package-conda.yml
name: Test plugins

on:
  pull_request:
  push:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          make install
      - name: Test with pytest
        run: |
          make meep
          make test-plugins
